name: pet_boarding_manager
description: A Flutter app for managing pet boarding
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
